# This is a basic workflow that is manually triggered

name: CI Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-node@v3
    - name: Checkout Azurite
      uses: actions/checkout@v4
    - run: npm install
    - run: npm run build
    - run: npm install -g
    - run: |
        mkdir -p testdir
        azurite -- -s -l ./testdir -d ./testdir/debug.log &
        sleep 5
        cat ./azurite/debug.log
